### ISSUE TITLE
QF - notify project owners when they are part of a new, active QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1026]
This can be a stretch goal / nice to have:

When a new QF round starts, we should send a notification to all project owners who have projects included in the round.

"< QF round  > is here and your project < project name > is in the round! Rally your community to donate before the round ends < round end date > :tada: "

**Comment by divine-comedian** [comment]
Need to add new template in notification center.

**Comment by laurenluz** [comment]
I would like just to email the projects, and maybe cut scope on notification centre

**Comment by jainkrati** [comment]
@RamRamez pls take this up

**Comment by RamRamez** [comment]
@laurenluz @divine-comedian Can you please clarify this issue? Do you need sending emails to be triggered automatically with impact-graph when new round starts? or like it to trigger it manually and you only need the list of project owners?
Because when projects are added to the round, we add a tag to project owners "QF project owner [round name]" in Ortto, so it should be easy to filter all users having that tag in Ortto and then sending the email to all of them.

**Comment by laurenluz** [comment]
let's loop @krmet in here as he is managing the new email system from the comms side. question
- with the new system, is it now going to be easy for us to find the list of "projects added to the QF round" w/ their emails? so that the manual step is just a "send"

right now, I am personally running around to make an email list to pass to Kareem to send the email out, and I hope we can make this more streamlined.

The issue was originally created talking about adding a notification to the notificatino center when a project is added to a QF round, and then I just hoped to cut scope on the notificatino centre.... and in the end... didn't we disable most of it? What is the story now w/ the notification center? Is it still kind of not working?

@RamRamez I;m debating if we really want this fully automated... because I actually think the copy of the email will change each round.

**Comment by divine-comedian** [comment]
We also have this issue here @laurenluz  that according to our testing is already done. 
This should add the tag to a project owner in the CRM when they are added to a QF round (and remove the tag if they are removed from a specific  round). This feature should enable you to filter our users by those who have the specific round tag and enable sending them an email. Does this fit your use case here? https://github.com/Giveth/impact-graph/issues/1291

**Comment by laurenluz** [comment]
yes I think that's better. then we can optimize the copy on the emails before they go out all at once, instead of having something generic.

if there are no objections, we can close this issue cc @koday1

**Comment by jainkrati** [comment]
@RamRamez pls guide @ae2079 for this issue, if any changes are pending

**Comment by RamRamez** [comment]
@jainkrati this issue is already done and owners list can be fetched from Ortto, so I think we can close this issue
