### ISSUE TITLE
Qf bugs 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1040]
I and @MohammadPCh  and @maryjaf  tested QF and found this backend bugs:
- [x] passport score return 0 most of time ( even when expect null)
One of these should return `null` another one `0`
* **0x4D0eA8BaAC3FEe45eF77776B492E4C6E97DD2332** 
*  **0x43D40fc3Ba8Ca44341C99652Ec609d327C2C8c4e**
- [x] When try to refresh pasport score od **0xcd192b61a8Dd586A97592555c1f5709e032F2505** passport score should be `2.81` but returns `4.81`(4.81 is the old score)

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  can you take this, I think it's related to gitcoinAdapter and `refreshUserScores` graphql query that you were working

**Comment by CarlosQ96** [comment]
Ill take it

**Comment by MohammadPCh** [comment]
Actually, we have 2 bugs:
1. the backend returns 0 for some accounts that actually don't have passport scores instead of null (I think somewhere in the backend we save 0 instead of null). 
2. if you change (we test decrease) your score in the passport, the refresh score API just returns the old one.
@maryjaf can explain test cases better than me :smile:

**Comment by CarlosQ96** [comment]
Found the issue, we have to resubmit the passport with the endpoint each time to refresh the scores. The other endpoints do not refresh it only retrieve it. 

Ill push a hotfix.

**Comment by CarlosQ96** [comment]
Also found the error with returning 0. Ill also work on it

**Comment by maryjaf** [comment]
> 2\. if you change (we test decrease) your score in the passport, the refresh score API just returns the old one.
>     @maryjaf can explain test cases better than me 😄

Thanks @car

> Actually, we have 2 bugs:
> 
> 1. the backend returns 0 for some accounts that actually don't have passport scores instead of null (I think somewhere in the backend we save 0 instead of null).
> 2. if you change (we test decrease) your score in the passport, the refresh score API just returns the old one.
>    @maryjaf can explain test cases better than me 😄

item 2 has been resolved, thanks @CarlosQ96 
but item 1 wasn't changed and when I sign in with an account that it hasn't passport account I see this message that related to user that has passport but the score is 0
<img width="1320" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/b75b40ca-1c8f-4e05-99c1-24b24ad3a268">

**Comment by CarlosQ96** [comment]
I can't fix that, after fixing #2, to refresh the score I have to resubmit passport. So i'm effectively always registering someone on gitcoin passport with their address, and if they haven't manually activated their stamps and logged in on passport the score will always be 0.

So from now on the score will be returned 0 always. 

Is this flow ok @MohammadPCh @MoeNick @maryjaf ? or should we change it?

**Comment by laurenluz** [comment]
@CarlosQ96 - to clarify, you're saying that... if a user is signed in on our dApp, we basically automatically create a passport for them with a score of 0?

If that's the case, I think we can just make some changes to the banner flow in order to accomodate that and save the backend work.

So: if the user doesn't have a sufficient score OR if they haven't manually set up their passport / have a score of 0 , we can just show this banner.... and elimiate the other banner saying they need to set up passport.

![image](https://github.com/Giveth/impact-graph/assets/75490971/da716b92-c624-4396-a605-f5884268de25)
