### ISSUE TITLE
Referral program modal in spanish -  missing title!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1048]
@mateodaza I think we are missing the translation fields for the referral program.

cc @MohammadPCh @MoeNick 
![image](https://github.com/Giveth/impact-graph/assets/75490971/62de7f13-aaed-44bf-99df-55e66c38e003)

**Comment by MohammadPCh** [comment]
@laurenluz  we did many things for translation:

- use English phrases if we don't have the translation
- use ChatGPT v4 to translate to Spanish and Catalan
- prepare JSON file to natives can approve the translation
 so this issue is fixed now and we show the English version if we don't have the translation. and also we translated it and waiting for approval.

**Comment by MoeNick** [comment]
@maryjaf pls again take a look

**Comment by maryjaf** [comment]
On production:

<img width="743" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/d723231a-2139-441f-ada8-bf25b6b623e5">
