### ISSUE TITLE
QF- Backend for having only one eligible chain in a QF round

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1126]

**Comment by MoeNick** [comment]
@maryjaf pls take a look.

**Comment by maryjaf** [comment]
Plz let me know when it's ready to test @CarlosQ96

**Comment by laurenluz** [comment]
just checking - this issue is for the backend changes to make only polygon donations eligible for matching?

Because if so, it would be great to add an option in admin bro where the admin can specify what chains are included in the round. i.e. admin can select "polygon", and then only donations made on polygon are included in the estimated matching calculations, and when the user tries to donate on other chains, we show them a message saying that "only donations on < polygon > are eligible for matching in this round".

I also need to work with @mosaeedi  for design for this.

@CarlosQ96 - can you confirm?

**Comment by CarlosQ96** [comment]
Yes the backend Pr is here: https://github.com/Giveth/impact-graph/pull/1124 its approved I shall merge it tonight. Just adding some minor things. I think ill add labels for the chain ids too in the adminjs. But how you said it is how it works on this PR.

**Comment by laurenluz** [comment]
you rock Carlos!

**Comment by maryjaf** [comment]
Plz check this @CarlosQ96 
I try to check the network or chain id on admin bro and set this for a round but by tapping on Qf round and QF round history I got this error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFNlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--005e2001d90315caddfc4c968a74ec6e485e4438/image.png)

**Comment by maryjaf** [comment]
> Plz check this @CarlosQ96 I try to check the network or chain id on admin bro and set this for a round but by tapping on Qf round and QF round history I got this error [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFNlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--005e2001d90315caddfc4c968a74ec6e485e4438/image.png)

Thanks @CarlosQ96 This issue has been resolved

**Comment by maryjaf** [comment]
Now the system behavior is like this:
When I create a round and set chainId on only polygon
when I donate on Gnosis this record isn't shown in the donation's round and only is shown in all donation correctly
but in donation page the estimated matching is shown and after donation the Quardatic funding box is shown as below pic
I think these issues are related to front changes, do we have any plan for changing these ? @laurenluz

<img width="923" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/2b3642eb-f7a7-47fc-a539-e88e30d9a51d">
 
<img width="1023" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/375122bc-3cf7-449e-b4f3-f4c7874c06c1">

**Comment by MoeNick** [comment]
@laurenluz pls take a look

**Comment by laurenluz** [comment]
@maryjaf - yes! we have an issue open for design to make these changes: https://github.com/Giveth/giveth-dapps-v2/issues/3178

Although, for the 1st point.. I think this may be related to back end, but I'm not sure. For all chains that are not "eligible" the estimated matching amount should just show as 0 🤔  @CarlosQ96 - is this just a frontend thing?

**Comment by CarlosQ96** [comment]
This should be handled from the frontend, if the project is in the round and the chain is not supported, show it as 0 in the frontend.
I can't change the estimated matching its not filtered by chains.

**Comment by laurenluz** [comment]
but then the estimated matching will be totally wrong? because it will be including/considering donations in the calculatino that are made on other chains?

**Comment by CarlosQ96** [comment]
Up to now, and even next Polygon round we handle 1 chain. So it's a non issue atm. Its a global matching fund per project

But we should work then on segmenting it per chain if that's what we want. Won't be a simple task but it's posible. We would need to change frontend and backend together to achieve this. Because its now a list of Matching funds per chain per project.

**Comment by maryjaf** [comment]
> Up to now, and even next Polygon round we handle 1 chain. So it's a non issue atm. Its a global matching fund per project
> 
> But we should work then on segmenting it per chain if that's what we want. Won't be a simple task but it's posible. We would need to change frontend and backend together to achieve this. Because its now a list of Matching funds per chain per project.

Do we work on it in this phase ? @laurenluz @CarlosQ96

**Comment by laurenluz** [comment]
> Up to now, and even next Polygon round we handle 1 chain. So it's a non issue atm. Its a global matching fund per project
> 
> But we should work then on segmenting it per chain if that's what we want. Won't be a simple task but it's posible. We would need to change frontend and backend together to achieve this. Because its now a list of Matching funds per chain per project.

we don't need to fix it for this round @maryjaf because we will only have 1 eligible chain = Optimism network. we probably won't even need to handle this for the next round, since again it will be just 1 eligible chain = Polygon!

this will need to be fixed before we can run rounds that consider like 2/5 chains (i.e. you can donate on Optimism OR Polygon), but I don't think we will need that for some time.

**Comment by laurenluz** [comment]
actually, looking at this, I think we might never need to make it possible to estimate the matching PER CHAIN. because we're going to be always distributing the matching funds on JUST ONE CHAIN.... so we should always consider the "global estimated matching", and never just the donations on one chain.

so I think that once this is all tested and approved as-is, there is no more work we need to do here!
