### ISSUE TITLE
Project slug is changed after an edition occurs 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#113]
following this [issue](https://github.com/Giveth/giveth-next/issues/122)

the slug adds a '-1' after the project is edited

**Comment by WhyldWanderer** [comment]
This seems to be an issue that many users are experiencing. The are multiple people in the Discord having problems with it.

Can we prioritize this issue?

**Comment by divine-comedian** [comment]
testing out projects changing the title and checking the slug 

https://next.giveth.io/project/what-happens-now

https://next.giveth.io/project/testing-the-title-change

unless there are any edge-cases this seems to work as intended? I suppose another question is that since the slug is changing will any old links forward to their new project? @mateodaza

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Now we save the slug history of user, so if you change your title ( and your slug as a result) , we have your previous slugs so the old links are valid, 
you can test it in this way, create a project, change the title , and then the new links and old links( means old slug) should refer to same project , like below links the two of them are referring to same project

https://next.giveth.io/project/slug-history-test-fourteen-three
https://next.giveth.io/project/slug-history-test-fourteen-five

And there was also another bug that I've fixed that in this issue, the bug was the slug wasn't unique, and we could have two projects with same slug and it was buggy, we don't have it anymore

**Comment by MoeNick** [comment]
💪💪👏 @mohammadranjbarz
