### ISSUE TITLE
Create database entry for Solana users & solana addresses

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1173]
Users who create profiles with only a solana address will need to be registered in our database. 

It will be possible that a user can only have a solana address and no ethereum address 
It is also possible a user with only a solana address could add an ethereum address to their profile at a later point

**Comment by jainkrati** [comment]
Yes we can add a new column representing blockchain type whose default value is ethereum and we specify solana when required. What do you think @aminlatifi

**Comment by aminlatifi** [comment]
> Yes we can add a new column representing blockchain type whose default value is ethereum and we specify solana when required. What do you think @aminlatifi

By looking again at the backend source code, I noticed a one-to-one relation between the user and the ethereum address! They are deeply coupled as `walletAddress` is a property (column) in the user entity and it has the string type.
So, the User entity and Ethereum address are deeply coupled in our design and I am afraid that filling the wallet address with a Solana address won't cause any issue in authenticating and other processes. 

I am thinking a short-term solution to meet the December 5th deadline would be defining two fields in the user Entity, `ethereumWalletAddress` and `solanaWalletAddress`, and keep the `walletAddress` and fill it with one of them which the user has signed in with! 

I don't opt for big changes in our design and like to make it with fewer possible changes since the `walletAddress` is extensively used in our logic and tests, and in this way, it would be possible to meet the V1 deadline.

**Comment by divine-comedian** [comment]
cc: @MoeNick

**Comment by MoeNick** [comment]
We have a problem in UX here that I shared with @divine-comedian and @mosaeedi before, the currant design is not backward compatible, it means if I go with only sign-in with Solana and I have an account on Giveth, dApp cant recognize who I am and will assume Im a new user, so I can't see my projects, profile, and transactions. 

I guess we need a change to make even sign-in with Ethereum mandatory, then we ask for users to add their Solana address if they want.

@mosaeedi is thinking about it right now. It affects the current flow @aminlatifi is implementing.

So @jainkrati I need a meeting with you guys to technically review that: if we have sort of jwt tokens in explorer storage, can we use it to manage the flow, at least it reduces the pain of bad UX and make the flow shorter, in this case I think @MohammadPCh can help.

**Comment by MoeNick** [comment]
Shall I put in progress or QA @aminlatifi

**Comment by aminlatifi** [comment]
> Shall I put in progress or QA @aminlatifi

We agreed to do it in January. Till then, the single `walletAddress` field stores the user address, either Ethereum or Solana.

**Comment by MoeNick** [comment]
It's ok for now I will create another issue for second phase.
