### ISSUE TITLE
Add solana address to projects

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1187]
We need backend support for the project's Solana address:
- Support Solana address as a project address in database schemas. In the current state, projects can have different ethereum addresses per chain, but they don't support Solana.
- Add/Edit API for adding/editing Solana address of a project

**Comment by MoeNick** [comment]
can we have it more generic, like non-evm addresses table? @aminlatifi 
we may have some of them for upcoming grants

**Comment by CarlosQ96** [comment]
We have a addresses table for projects we can re-use it. I think this might take just a few **3-4 hours.** 
And modify the api where we edit addresses. So ill add another 1-2 hours.

Total: **6 hours.** (Max 8 hours -> a day rightfully tested)

This issue is part of a bigger one: https://github.com/Giveth/impact-graph/issues/1188 which is making a donation to a project address.
