### ISSUE TITLE
Admin Dashboard Integration with AdminBro framework

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#138]
Related to #207
Test scenarios of listing are there.

**Comment by MoeNick** [comment]
Acceptance criteria - an admin user can:
0- Login and log out with its own wallet
1- See all projects
2- Sort, search and filter within title, create date, project manager, and status of listig, verification and activeness
3- See score of the projects as hearts etc... 
4- see listing, verification and activeness of the projects in list and in detail of a project
5- change listing, verification, activeness of the project. by one one or in bulk.
6- for trace projects de-active means archiving in trace database. listing should handle in io data base and verification has the same meaning with io on trace db.

**Comment by MoeNick** [comment]
@mohammadranjbarz the number 6 above, is the matter we talked about it. we have a hack-sesh about this on Wed. pls updated the card right after the meeting or feel free to add related issues to this card.

**Comment by mateodaza** [comment]
We are only missing the segment actions, created an issue for it [#152]([https://github.com/Giveth/impact-graph/issues/152])

**Comment by MoeNick** [comment]
Who did test it @mateodaza ?

**Comment by MoeNick** [comment]
@divine-comedian mention you here to test and make sure everything is set.

**Comment by divine-comedian** [comment]
testing on the admin dashboard and `next.giveth.io`
brave browser, clean cache and cookies

**can only log in with username and password (instead of ethereum wallet address)**

I can see hearts and quality score of each project
sorting works great! 

**can't see if the project is traceable from the admin dashboard**

successfully verify single/multiple projects

successfully unverify singe/multiple projects 

successfully cancel single/multiple projects 

successfully activate single/multiple projects

successfully activate/cancel/verify/unverify an old project (march 2021)


**currently I can unverify a traceable project and it still shows with the traceable badge on IO, I can also find it on the campaign list on `develop.giveth.io` (TRACE staging).**

**Comment by MoeNick** [comment]
@mateodaza @CarlosQ96 ping you here again just to make sure we have a confirmation from mitch side.

**Comment by MoeNick** [comment]
If the problems are just related to trace, we can skip them, lemme have a talk with @WhyldWanderer to have a confirmation from her side.
