### ISSUE TITLE
Base | Summation of donation from all chains including base. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1578]
Just created this issue to make sure and test the donations counts in
- Projects card raised amount
- My account - DONATIONS RECEIVED
- Public profile page
- My account TOTAL AMOUNT DONATED
- My account TOTAL Donations

**Comment by maryjaf** [comment]
- I donated 3.82 $, "all donation" in donation tab is increased correctly based on my donation
but "total raised" in project detail isn't increased correctly based on 3.82 $ 
but this problem isn't exactly related to this issue , this problem was resid in  #1566

Before donation:
Total Raised $640.92

<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40eeb803362173268eddfc0ce2a762a1e80db01f/image.png" alt="image.png" />

after donation:
Total Raised $648.51

<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2djQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f9e2788e674f68ecafe40f04c33c380585ab669/image.png" alt="image.png" />
