### ISSUE TITLE
Create a unique and single wallet per GivingBlocks Project for making donations on the Giveth Website.

### ISSUE THREAD

**Issue by cquinterom096** [Giveth/impact-graph#158]

**Comment by divine-comedian** [comment]
how can I test this issue? @CarlosQ96

**Comment by CarlosQ96** [comment]
@divine-comedian well it's a bit complicated to test manually. However, in staging I left the process that synchronizes with the giving blocks running every hour. So if there are no duplicated projects this worked.
The reason is I set up an INdex/rule on the database that addresses need to be unique. 
So if another project tries to use that address, it throws and exception and skips that project.

I think if you don't find any duplicates, this issue can be closed. But yeah there should be 700-750 projects added I don't think there is any duplicated as I verified with Mohammad.

**Comment by CarlosQ96** [comment]
It wouldn't be posible with a database rule.

**Comment by CarlosQ96** [comment]
Also Gemini generates a different address per project. After synchronizing locally like 30 times, it never generate the same address for two projects.

**Comment by divine-comedian** [comment]
okay great! looks to be tested then - moving to DONE
