### ISSUE TITLE
Get verified projects that have added an OP address - DROP 9

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1695]
@mohammadranjbarz you know the drill! We should fetch verified projects that have added an OP recipient address in order to airdrop a new batch of incentives - similar to #1155

**Comment by mohammadranjbarz** [comment]
@divine-comedian Just keep it in your mind, once we import Endaoment projects this query will return few thousand records, because all Endaoment projects are verified and have OP address as well, maybe you decide to exclude those projects for next drops

# Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```
# Result

[verified_projects_with_op_address_july_2024.csv](https://github.com/user-attachments/files/16319837/verified_projects_with_op_address_july_2024.csv)
