### ISSUE TITLE
GIVpower boosting showing as NaN

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1702]
A user reported an issue where they have a GIVpower boosting showing as `NaN` which causes their total GIVpower to respond as `NaN`

![Image](https://github.com/user-attachments/assets/0f03c2a8-47f6-4500-9082-dc8a961b9b14)

IIRC we had a similar issue present itself a few weeks ago that @aminlatifi  resolved, how is it that this can happen?

**Comment by divine-comedian** [comment]
@WhyldWanderer says 

> Carlos recently helped me to transfer this project from one owner address to another... I wonder if this transfer could have caused an issue somewhere in the backend

**Comment by aminlatifi** [comment]
> @WhyldWanderer says
> 
> > Carlos recently helped me to transfer this project from one owner address to another... I wonder if this transfer could have caused an issue somewhere in the backend

@WhyldWanderer @CarlosQ96 Did that change include changing the user address?! I see the positive givpower for that user in the past, but now it doesn't have any balance (the new address haven't made any tx neither on gnosis nor optimism mainnet)

**Comment by aminlatifi** [comment]
BTW, it can be fixed by https://github.com/Giveth/impact-graph/issues/1655

**Comment by WhyldWanderer** [comment]
It was actually a pretty confusing situation with this one project.. 

Quite a while ago they asked to change the wallet address on their profile.. we did it and it seemed successful. 

Then they came back at a later time and were unable to edit their project.. they could log in a nd see their project but couldnt make changes so they opened a support ticket.
It turned out that they actually had 2 profiles with the same wallet address. 
One that had a mixture of capital and lowercase letters and the other just had lowercase letters in the same format that we use in the database. 

I asked them which profile they wanted to use going forward and changed the address for that profile to be the one with lowercase letters and on the other profile I entered a random wallet address because I was told that we don't want to delete anything in the db.

Ugh.. Im sorry this is such a mess and so confusing.. 
These were the two profiles:
![image](https://github.com/user-attachments/assets/2cbdaf6b-433a-46c7-892d-fa4d9c95c4da)

They decided to keep the 10381 profile..
So i edited the address to have all lowercase letters and I changed the other wallet address to this random one.
My guess is that the NaN is showing for the profile that they chose not to keep.

I realize that this wasnt the best practice and I even talked with Carlos a bit about me not transferring ownership of projects in the future because it seems to cause weird issues that we arent prepared for when its done through AdminBro. It seems to change the admin ID on some tables but not others in the db. We agreed after this incident that I would always ask a dev to do it manually when going forward.

I just hate to bug devs with something simple and make project owners wait for the transfer to be complete. 
Maybe its time to re-evaluate how this works and make sure it is something that can be done smoothly in the adminbro?

**Comment by divine-comedian** [comment]
Yep, transferring profile ownership is on my to do list! 

Just so you know - the difference in capitalization between addresses is often attributed to checksumming - https://cointelegraph.com/explained/ethereum-address-checksum-explained - which is not as straightforward as capitalizing or lower casing all the letters.. it is a complex algo involved in checksumming adresses.. 

At anyrate hopfully @aminlatifi can find the fix

**Comment by aminlatifi** [comment]
@WhyldWanderer @divine-comedian in impact-graph we have decided to save everything in lowercase. So, everytime you want to insert addresses or transaction hash, transform it to lower case.
The above issue originally was happened since this rule was not observed.
CC @jainkrati One way to prevent this is adding some constraint in db to prevent such data be saved 
https://stackoverflow.com/questions/9046825/postgresql-auto-lowercase-text-while-or-before-inserting-to-a-column

**Comment by aminlatifi** [comment]
@WhyldWanderer Okay, I removed every boosting associated to user 12130
Now the project ranking is fixed
https://giveth.io/project/soildao-steward-platform?tab=givpower
