### ISSUE TITLE
When Users attempt to donate with Solana Devnet, the calculations for Giveth Givbacks after selecting any of the percentage is not correct (the amount being donated to Giveth shown on the preview modal is also wrong)

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/impact-graph#1710]
Given that Users have connected their wallet and Signed In.
And the Network is Solana Devnet
And Users have inputted the number of tokens to be donated
When Users select a percentage to be donated to giveth
Then the Giveth donation calculated amount is still equal to the amount being donated to the Project

![Screenshot (148)](https://github.com/user-attachments/assets/4b9a6b97-f218-48c2-a3b4-82d768cc3d77)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - you can confirm this only applies when on solana devnet? no other chains are affected by this bug?

@MohammadPCh - can you check this out or delegate it to another FE dev?

**Comment by divine-comedian** [comment]
@MohammadPCh - can you check this out or delegate it to another FE dev?

**Comment by LatifatAbdullahi** [comment]
> @LatifatAbdullahi - you can confirm this only applies when on solana devnet? no other chains are affected by this bug?
> 
> @MohammadPCh - can you check this out or delegate it to another FE dev?

Yes, only on Solana Devnet

**Comment by MohammadPCh** [comment]
@lovelgeorge99 could you please take this? Thanks

**Comment by lovelgeorge99** [comment]
ok i will work on this 👍

> @lovelgeorge99 could you please take this? Thanks

**Comment by maryjaf** [comment]
Could you please take a look on this comment 
@lovelgeorge99 
https://github.com/Giveth/giveth-dapps-v2/issues/3903#issuecomment-2267570142

**Comment by lovelgeorge99** [comment]
@maryjaf 

![Image](https://github.com/user-attachments/assets/a84daba1-964d-4420-b3a9-7e98d331af01)


Earlier the logic was if the user is trying to donate `0.000001` , the giveth donation would automatically change to 0.000001 also(that is the minimum donation amount ) and total donation would be  `0.000001 + 0.000001 = 0.000002` .
Since the users total donation is only `0.000001` ,he cant donate `0.000002` .

Now the new logic is that if the user is trying to donate a amount less than the minimum giveth donation amount ,giveth donation is converted to 0


![Image](https://github.com/user-attachments/assets/2b8a6103-a2d1-455c-887e-d21c25e36fe2)

**Comment by maryjaf** [comment]
Thanks @lovelgeorge99 
Is this new logic and UX approved by @divine-comedian also?

**Comment by divine-comedian** [comment]
Sorry I don't understand clearly what is explained. Is it this?

- Minimum amount that can be entered on the donation input is `0.000001`
- user enters to donate minimum amount - `0.000001`
- has selected donate % to Giveth

Since we can't accept numbers under the minumum (e.g. `0.000001 * 5%`) the giveth donation amount is then rounded up to the minimum amount? 0.000001. This means the user ends up donating 0.000002 ? 

If this is true then what we should do check the box for "I do not want to support Giveth . . . " to ensure no second tx is generated and the text shown on the page makes sense.

**Comment by maryjaf** [comment]
> Sorry I don't understand clearly what is explained. Is it this?
> 
> * Minimum amount that can be entered on the donation input is `0.000001`
> * user enters to donate minimum amount - `0.000001`
> * has selected donate % to Giveth
> 
> Since we can't accept numbers under the minumum (e.g. `0.000001 * 5%`) the giveth donation amount is then rounded up to the minimum amount? 0.000001. This means the user ends up donating 0.000002 ?

This is the previous behavior of system in donation page, 
the current behavior is like as below video 

https://github.com/user-attachments/assets/de6820fb-564d-4c1c-9568-b939194f864c

My question is, even though the user has chosen a percentage and "Donating 15% to Giveth: 0 GIV" is shown,  is the behavior accepted? @divine-comedian 
- Enter 0.000001 GIV for donation
- Select 5 or 10,15 20 % for donating to Giveth 
- "Donating % to Giveth" is set 0 

![image](https://github.com/user-attachments/assets/c15ab18b-d012-4193-a217-1da5b63c8976)

**Comment by divine-comedian** [comment]
yes @maryjaf

**Comment by maryjaf** [comment]
This change should be reverted 
@divine-comedian @lovelgeorge99 
cc: @MohammadPCh 

https://github.com/user-attachments/assets/c0cf023a-6876-4f15-86b6-63c4c0c521ee

**Comment by kkatusic** [comment]
@maryjaf you used Trust wallet? thx

**Comment by lovelgeorge99** [comment]
> @maryjaf you used Trust wallet? thx

https://github.com/user-attachments/assets/44614c26-5c1f-476e-aab6-41ce1e8e9e69

**Comment by maryjaf** [comment]
> > @maryjaf you used Trust wallet? thx
> 
>  2024-08-12.10-40-37.mp4

No I tested it on Metamask

**Comment by maryjaf** [comment]
> > Sorry I don't understand clearly what is explained. Is it this?
> > 
> > * Minimum amount that can be entered on the donation input is `0.000001`
> > * user enters to donate minimum amount - `0.000001`
> > * has selected donate % to Giveth
> > 
> > Since we can't accept numbers under the minumum (e.g. `0.000001 * 5%`) the giveth donation amount is then rounded up to the minimum amount? 0.000001. This means the user ends up donating 0.000002 ?
> 
> This is the previous behavior of system in donation page, the current behavior is like as below video
> 
>  Screen.Recording.2024-08-11.at.11.51.06.AM.mov 
> 
> My question is, even though the user has chosen a percentage and "Donating 15% to Giveth: 0 GIV" is shown, is the behavior accepted? @divine-comedian
> 
> * Enter 0.000001 GIV for donation
> * Select 5 or 10,15 20 % for donating to Giveth
> * "Donating % to Giveth" is set 0
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/356862209-c15ab18b-d012-4193-a217-1da5b63c8976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzQyNDEsIm5iZiI6MTcyMzQ3Mzk0MSwicGF0aCI6Ii8xMTE1MjkxODUvMzU2ODYyMjA5LWMxNWFiMThiLWQwMTItNDE5My1hMjE3LTFkYTViNjNjODk3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxNDQ1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTMyNjBkZmVlMmFjZDBkOTExN2IzMGE3MDg4N2I4ZDM0MDFjOTg4NTE3MTk3NWY0NzgxYjc0NWU5MGNjMTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RbS9QTYa11U2vZ-QRsYf9mKg96Fo8uE-BeMPRQAY0Xw)

Actually the problem is related this new logic, in this scenario that user enters 0.000001( minimum amount of donation) and select a percentage for donating to Giveth 
Based on new logic , the amount of donation to Giveth is set 0 and the reported bug happens

**Comment by kkatusic** [comment]
@divine-comedian this is how thing are sorted up, minimal GIV donation is 0.000001 (read 5 decimals zeros) and for example 5% of GIV donation to Giveth is 0.00000005 GIV (read 7 decimals zeros). App than setup GIV 5% donation to 0 and that's why the transaction fails. Why did someone implement this code, maybe there was some request for it.

Now what you want to do, to allow small amount of GIV token donation to Giveth if someone add smallest amount of "main" donation, or we can than reset the GIveth donation amount to minimal token donation amount, in this previous case it was 0.000001 ?

thx

**Comment by divine-comedian** [comment]
chatted with kechy - since this feature/bug isn't super important so let's go the way of least headache. 

If the minimum donation amount if set we should set the giveth donation amount to 0 and ensure the UI elements reflect this. 

 - toggle the checkbox on the UI to "I don't want to make a donation to Giveth" and make sure the numbers on the UI are correct
 - ensure there is no amount entered on UI for "donating to Giveth"

![image](https://github.com/user-attachments/assets/2232b513-587d-467a-ad96-88259f722933)

**Comment by divine-comedian** [comment]
@kkatusic what is the update on this issue?

**Comment by kkatusic** [comment]
> @kkatusic what is the update on this issue?

this is waiting PR review :( I will ask for review

**Comment by kkatusic** [comment]
@LatifatAbdullahi you can test when you get time ;)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

**These have been fulfilled**
- Set the giveth donation amount to 0 and ensure the UI elements reflect this - **Pass**
- Toggle the checkbox on the UI to "I don't want to make a donation to Giveth" and make sure the numbers on the UI are correct - **Pass**
- Ensure there is no amount entered on UI for "donating to Giveth" - **Pass**

**However at the point of Donation confirmation, it takes too long to confirm donation, over a minute, it just keeps loading continuously and my wallet is deducted without a success modal**.



https://github.com/user-attachments/assets/4d038e8c-9776-48fb-bd69-575d55d5ae71


https://github.com/user-attachments/assets/8e53b13b-2271-44dd-9e16-e4fcd43f66f7


![image](https://github.com/user-attachments/assets/73374928-97b4-4fa3-a953-033dd9e1bef0)




![sss](https://github.com/user-attachments/assets/e8d492a1-5544-4bac-af50-4ab2b75324ca)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this is already done?

**Comment by LatifatAbdullahi** [comment]
@kkatusic 
The issue is not fixed

![image](https://github.com/user-attachments/assets/30bfee77-dfbe-4ee7-a49c-7fec40c5d94d)

**Comment by kkatusic** [comment]
@LatifatAbdullahi, ccc @divine-comedian, making donation on Solana DevNet is old issue, we didn't manage it to work, I also reported that issue on package github account:

https://github.com/anza-xyz/wallet-adapter/issues/1009

I tried and succeeded to made donation on SOlana project on production and it is working fine, check images:

![Screenshot 2024-10-03 at 11 55 34](https://github.com/user-attachments/assets/eab421cd-6d86-4dfc-bc4c-6b3ff2ca95e0)
![Screenshot 2024-10-03 at 11 54 56](https://github.com/user-attachments/assets/7e6e2a1d-73bb-4146-b70b-84ba255000a2)
![Screenshot 2024-10-03 at 11 55 07](https://github.com/user-attachments/assets/3863081b-a301-4408-8057-fbf4b24e6ea3)
![Screenshot 2024-10-03 at 11 55 31](https://github.com/user-attachments/assets/a9f9f5ae-0eda-4499-9282-35b69429ef6d)

you decide will we wait to they fix devnet transaction problem or we will close this issue

**Comment by divine-comedian** [comment]
honestly, not very important to get solana devnet perfect, if we are sure production is working OK I think we can move on!
