### ISSUE TITLE
Ensure Revoke Badge button in adminJS is handled correctly

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1846]
in the project tab when a project is selected there is a "revoke badge" button -  we should make sure of two things:
- the isGIVbacksEligible status of this project is set to false when the badge is Revoked
- the verified status of this project is unchanged

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify this part:
* the isGIVbacksEligible status of this project is set to false when the badge is Revoked
* the verified status of this project is unchanged

NOTE: the revoke badge is not moved to verification form tab, it's still in project tab

**Comment by divine-comedian** [comment]
@RamRamez moved the issue for moving the button placement to a new issue -> https://github.com/Giveth/impact-graph/issues/1854

**Comment by LatifatAbdullahi** [comment]
@RamRamez @divine-comedian 
**Admin**  

Givback Eligible status: **True**
Vouched: **True**

Action: Revoke Givback Eligibility

Result - **Pass**
Givback Eligible status: **False**
Vouched: **True**



**FE**
On the Admin this is confirmed working as expected, but when the the Givback Eligibility is revoked, shouldnt the FE status show "Ineligible" ?? because after I revoked the status its currently showing "Incomplete" on the FE @divine-comedian  @mateodaza

**Comment by divine-comedian** [comment]
it depends on the status of your form - so if givbacks eligible is false it will look at the status of your application form
so this is an acceptable outcome.
