### ISSUE TITLE
The valueUsd is not filled for GIV donations

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#276]
You can see lots of these donations with this query

```
select * from donation
where currency='GIV'
```

or here
https://giveth.io/project/Diamante-Bridge-Collective-0

**Comment by mohammadranjbarz** [comment]
@mateodaza  This PR https://github.com/Giveth/impact-graph/pull/275 will fix this issue?
I should not do something?

**Comment by MoeNick** [comment]
DO we need the USD value for old GIV donated? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> DO we need the USD value for old GIV donated? @mohammadranjbarz

I remember that Mateo or Carlos implement a cronjob for updating donations  `usdValue`, so if I'm not mistaken it would resolve old donations, but I couldn't find that in the codes, @mateodaza can you help us?

**Comment by CarlosQ96** [comment]
@mohammadranjbarz Mateo added Giv to monoswap yesterday so new donations should work now.
However for old ones we must write the script, the script doesn't exist.

This will also be specially helpful for tokens that don't appear on monoswap, since we allow them now.

I lookup with Mateo some apis like coingecko (but this one is too limited, gotta pay to use effectively). But we should probably look a varios options that would work side by side monoswap library, and the script would run everyday to update those values.

Didn't write the script because we were unsure which api to use.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Mateo added Giv to monoswap yesterday so new donations should work now. However for old ones we must write the script, the script doesn't exist.
> 
> This will also be specially helpful for tokens that don't appear on monoswap, since we allow them now.
> 
> I lookup with Mateo some apis like coingecko (but this one is too limited, gotta pay to use effectively). But we should probably look a varios options that would work side by side monoswap library, and the script would run everyday to update those values.
> 
> Didn't write the script because we were unsure which api to use.

Thanks Carlos

@MoeNick  Should we create another story for what should we do for older donations?
( As Carlos said, I think it's not an easy or routine job, so it might need a little discussion as well)

**Comment by MoeNick** [comment]
would u pls update this issue guys?
