### ISSUE TITLE
GIVbacks Calculation Script - Consider dates of verification status 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#407]
The project verification team awards badges at the beginning of each round.

The review team cannot run the scripts until after the round ends so we are capturing incorrect data.

The problem:
When the review team runs the scripts for Round 5 data (eligible donations), it is including donations that were made to projects that were not verified yet when the donations were made. 

We need to consider the dates that projects were verified and exclude any donations made to projects before they received the badge.

**Comment by mohammadranjbarz** [comment]
I have better idea , instead of tracking history of status changing of projects, I will put a field in donation named  `isProjectVerified`, and if the project is verified at the  time of the creation of donation I set `true` for that field , and in givback script I use this field to know if donation is eligible or not, it's very easier to implement
