### ISSUE TITLE
verification - show checked icon when email is verified

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#567]
When user clicks verify email, personal info get a checked badge. The checked badge should be shown when user has verified the email. We show checked badge based on last step so when user hasn't verified email yet, last step should be `before you start`

@mohammadranjbarz @CarlosQ96 

![image](https://user-images.githubusercontent.com/73441857/179787076-2a2c4978-6192-4ed5-b0a6-7ba660e68087.png)

**Comment by mohammadranjbarz** [comment]
After sending each step data we marked that step as done and we change the last step but in personal info after filling the email and sending personal info data you need to verify the mail, so we should change flow of updating lastStep, it may affect the whole flow, so if we want to release these days I recommend don't change it and fix it for next release, because it needs lots of testing(maybe writing more automatic tests) to make sure doesn't break other things,
@MoeNick  what do you think?

**Comment by MoeNick** [comment]
Let's have a talk about this in the daily @RamRamez @RamRamez @MohammadPCh

**Comment by RamRamez** [comment]
@mohammadranjbarz The other problem that I have is the `managing funds` step doesn't have the checked badge. I think backend doesn't update last step for that.

![image](https://user-images.githubusercontent.com/73441857/179956253-d1cb6c1c-48a2-43ed-9cb2-b046904c419a.png)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz The other problem that I have is the `managing funds` step doesn't have the checked badge. I think backend doesn't update last step for that.
> 
> ![image](https://user-images.githubusercontent.com/73441857/179956253-d1cb6c1c-48a2-43ed-9cb2-b046904c419a.png)

@RamRamez  Thanks for reporting this issue , I fixed it, it's deployed on staging ( the reason is that in the backend `managingFunds` step was before milestones, so updating `managingFunds` didn't update`lastStep`)

<img width="1857" alt="Screen Shot 1401-04-29 at 16 53 42" src="https://user-images.githubusercontent.com/9850545/179981083-89580c53-d37a-410b-a451-f60f81528913.png">

**Comment by mohammadranjbarz** [comment]
@RamRamez  Now if user is not confirmed the email we should set `null` as their step so frontend will redirect it to first step ( personal info)
It's on staging now, you can test it

**Comment by RamRamez** [comment]
@mohammadranjbarz after user confirmed the email, you should change last step, but now it doesn't change

![image](https://user-images.githubusercontent.com/73441857/181288724-28fbf8aa-ec59-45d7-ae70-d610248957f8.png)

![image](https://user-images.githubusercontent.com/73441857/181288817-e883f3b6-ba33-4cd7-ab76-81a4ef4493fd.png)

**Comment by CarlosQ96** [comment]
I added the laststep update in the email confirmation, CI-CD deploying

**Comment by CarlosQ96** [comment]
@RamRamez Its up in staging you can test when verifying an email it should set the laststep to "profileInfo"

**Comment by RamRamez** [comment]
Thanks. It's ok now.

**Comment by giantkin** [comment]
Testing on https://staging.giveth.io/verification/test-isuee-1  Goin through flow, completing each step, CHECK icon showed on each. 
![image.png](https://images.zenhubusercontent.com/62f673323e5f851807aa0fdc/5a5df57d-a10a-4c33-bdca-9b5e87df5b7b)

**Comment by divine-comedian** [comment]
looks good moving to done!
