### ISSUE TITLE
Capture status change events in edit project page in admin bro

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#729]
When user changes **verified**, **listed** or changing status of projects to one **activated** , **deactivated** and **cancelled** we should send notification (and email if it's needed) 

<img width="1439" alt="Screen Shot 1401-08-26 at 12 05 03" src="https://user-images.githubusercontent.com/9850545/202456723-40929cdd-1ca1-41b3-8fbd-ca1ad832632d.png">

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick 
It's on staging now

**Comment by maryjaf** [comment]
> @maryjaf @MoeNick It's on staging now

I think this problem is not completely solved @mohammadranjbarz 
Because when I change the project from the edit page to the listed status, I do not receive a notification
But when I make this change from the list, I receive this notification: Nice! Your [testfilterr](https://staging.giveth.io/project/testfilterr) project is listed.


When I unlist the project from the edit page, I get a notification as a who that like this project not project owner (i liked my project): The [testfilterr](https://staging.giveth.io/project/testfilterr) that you liked is no longer visible. 
and when unlist project from list i receive two notification as who liked project and project owner :
The [testfilterr](https://staging.giveth.io/project/testfilterr) that you liked is no longer visible.
6 seconds ago
Your [testfilterr](https://staging.giveth.io/project/testfilterr) project is no longer visible.
6 seconds ago

----
And in general, now we don't get notified based on the status change, if I just click, I get notified
For example, the status of my project is listed, if the admin user hits the list again, even though the status has not changed, a notification will be sent.
is that ok? @mohammadranjbarz @MoeNick

**Comment by mohammadranjbarz** [comment]
> > @maryjaf @MoeNick It's on staging now
> 
> I think this problem is not completely solved @mohammadranjbarz Because when I change the project from the edit page to the listed status, I do not receive a notification But when I make this change from the list, I receive this notification: Nice! Your [testfilterr](https://staging.giveth.io/project/testfilterr) project is listed.
> 
> When I unlist the project from the edit page, I get a notification as a who that like this project not project owner (i liked my project): The [testfilterr](https://staging.giveth.io/project/testfilterr) that you liked is no longer visible. and when unlist project from list i receive two notification as who liked project and project owner : The [testfilterr](https://staging.giveth.io/project/testfilterr) that you liked is no longer visible. 6 seconds ago Your [testfilterr](https://staging.giveth.io/project/testfilterr) project is no longer visible. 6 seconds ago
> 
> And in general, now we don't get notified based on the status change, if I just click, I get notified For example, the status of my project is listed, if the admin user hits the list again, even though the status has not changed, a notification will be sent. is that ok? @mohammadranjbarz @MoeNick

I didn't get this part of your comments 
>> if I just click, I get notified
For example, the status of my project is listed, if the admin user hits the list again, even though the status has not changed, a notification will be sent.

Can you give me a screenshot about it?

@MoeNick  Yeah Maryam is right, we have problem that didn't think about it, if some is owner of the project, liked the project and donated to that, will receive 3 notification on some events, what should we do in these cases?
(There would be some other variations as well, for instance someone who liked and donated to a project, or someone who ownes and donated, ...)

**Comment by maryjaf** [comment]
when I changed status of project or listed/unlisted from edit page I didn't receive notification and email @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> when I changed status of project or listed/unlisted from edit page I didn't receive notification and email @mohammadranjbarz

@CarlosQ96  has fixed that and we deployed it.
@maryjaf please test it again

**Comment by maryjaf** [comment]
> > when I changed status of project or listed/unlisted from edit page I didn't receive notification and email @mohammadranjbarz
> 
> @CarlosQ96 has fixed that and we deployed it. @maryjaf please test it again

Thanks @CarlosQ96 @mohammadranjbarz 
I tested Notification and the emails that we tested earlier and it was OK from the list, now it has passed  in the **edit page** as well.


Below scenario also needs to be checked, but it is clearly not related to the edit page. If it is necessary to comment on another issue, let me know.
-We have notifications **that are sent to the project owner, but not to those who liked the project** (both the list page and edit page)

- Listed project
- Activate project
- Verify/Unverify

**Comment by mohammadranjbarz** [comment]
> 

I would appreciate it, if you can make separate issues for each item that you mentioned

**Comment by mohammadranjbarz** [comment]
> > 
> 
> I would appreciate it, if you can make separate issues for each item that you mentioned

@maryjaf

**Comment by maryjaf** [comment]
> > > 
> > 
> > 
> > I would appreciate it, if you can make separate issues for each item that you mentioned
> 
> @maryjaf

Sure,
https://github.com/Giveth/notification-center/issues/22

**Comment by MoeNick** [comment]
related to #809 beacyse we changed the subscribers concept
