### ISSUE TITLE
impact-graph restart on env config issues

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#870]
If a variable is missed in the config (.env file) the docker image keeps restarting

**Comment by MoeNick** [comment]
@mhmdksh it will be by next changes on env configs

**Comment by CarlosQ96** [comment]
Removing my self from this issue as its part of the what @mhmdksh presented this morning and probably a better solution.

**Comment by mhmdksh** [comment]
@MoeNick @aminlatifi I don't see how this error is related to how things are hosted or how we check things in our pipelines. To me, this seems like an error handling issue.

**Scenarios**:
```
1. Start Command --> ENV Available? ---> YES --> App Starts Successful
2. Start Command --> ENV Available? ---> NO --> App Won't Start
```

However, handling ENV Errors should not be a problem when using Vault, it will help a lot tracking the missing ENVs

**Comment by MoeNick** [comment]
Can someone update me about status of this issue? is it still valid?

**Comment by MoeNick** [comment]
I added to technical debts epic, is it still valid?

**Comment by mhmdksh** [comment]
@MoeNick @divine-comedian There is no enough context to what this issue is about or how it can be reproduced. Also we already have an auto-restart policy for our deployments when anything wrong happens. As well as an around the clock monitoring for logs and app health.

This is mostly done by error handling and cannot be solved by us.

Please feel free to close the issue
