### ISSUE TITLE
Calculate reward for chainvine referral donations

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#904]
related to https://forum.giveth.io/t/chainvine-referral-program/910

1. Referral reward is 10 percent ( we put this percentage in config to can easily change it) of givback reward ( after calculating  givback factor)

2.  Purple list doesn't affect referral reward ( FYI purple list addresses are not eligible for getting givbacks)

3. We send reward for those donations that are eligible for givback ( for instance if someone donate to unverified project we don't send reward for referrer)

4. New donor dilemma
4.1.  Also, another point is do we want to only let the program run for “new donors”? If so, we need to make sure that a user is donating for the first time, before we count them as a referral.(questioned by @ahmadabugosh )
4.2 What should we do about users that are already in our DB but didn't donate yet and now donate with a referral link

Please correct me if I'm mistaken.

@MoeNick 
I can jump to this issue anytime you say

**Comment by GriffGreen** [comment]
1-3 are great! We might debate the % in the forum but knowing its easy to change is great!

New donor dilemma
4.1. Also, another point is do we want to only let the program run for “new donors”? If so, we need to make sure that a user is donating for the first time, before we count them as a referral.(questioned by @ahmadabugosh )

4.2 What should we do about users that are already in our DB but didn't donate yet and now donate with a referral link

IMO, irregardless of any devwork involved, if i had to design this system...

If the donor is new, then the Referal gets 10% of their GIVbacks for the rest of this round and the next round. 

If the donor is not new, but they click the link, the referrer should get the 10% of their GIVbacks THAT 24HR period. 

I assume there is development consideration here.... so that may not be possible... but thats what makes sense to me.

**Comment by ahmadabugosh** [comment]
Hey @mohammadranjbarz , 

For 1) I think we're going to raise it to 50% to encourage participation in the beginning of the program (@GriffGreen suggested this in the forum) 

2) Yes, Purple list projects can still get GIVbacks (if it's through referrals)

3) True, the same GIVbacks rules apply, it needs to be a verified project. 

4) I agree with Griff, I think (if it's possible)

4.1) New donors get rewards for this current round and the next round (2 rounds). 
4.2) For donors that already donated, referral donations would apply just for that 24-hour period. I think this should also apply to users we have in our database that didn't donate yet (since they would have already known about us and it's just about re-engaging).

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  has implemented impact-graph side and I implemented givback-calculation side, now it's implemented and deployed on https://givback.develop.giveth.io/api-docs/#/default/get_calculate, @divine-comedian  as you are the best one who is familiar with givback-calculation API I would appreciate if you can test it

1. We use a fraction of eligible donations to referrer if donations is referral ( now it's 10 percent but its configurable)
2. It doesn't matter if referrer is in purple list or not, we distribute reward for him
3. If the user that came with the referral link is a new donor we will give a referral reward to the referrer for the current round and the next round
4. If the use that came with the referral link is not a new donor we will give reward for next 24 hours ( 24 hours from when user clicked on link, and also the time is configurable)
5. example: user **A** make a donation with 100$ value, **A** send a referral link to user **B** and that user donate to a verified project with 200$ value, now when calculating givback reward we assume, user **A** has donated (100 + 10% * 200) = `120$`  and user **B** has donated 200 * 90% = `180$` and we calculate givbacks based on this info

**Comment by divine-comedian** [comment]
> @CarlosQ96 has implemented impact-graph side and I implemented givback-calculation side, now it's implemented and deployed on https://givback.develop.giveth.io/api-docs/#/default/get_calculate, @divine-comedian as you are the best one who is familiar with givback-calculation API I would appreciate if you can test it
> 
> 1. We use a fraction of eligible donations to referrer if donations is referral ( now it's 10 percent but its configurable)
> 2. It doesn't matter if referrer is in purple list or not, we distribute reward for him
> 3. If the user that came with the referral link is a new donor we will give a referral reward to the referrer for the current round and the next round
> 4. If the use that came with the referral link is not a new donor we will give reward for next 24 hours ( 24 hours from when user clicked on link, and also the time is configurable)
> 5. example: user **A** make a donation with 100$ value, **A** send a referral link to user **B** and that user donate to a verified project with 200$ value, now when calculating givback reward we assume, user **A** has donated (100 + 10% * 200) = `120$`  and user **B** has donated 200 * 90% = `180$` and we calculate givbacks based on this info

Understood, however since we mix in referral donations with all the other donation data (on production) it is hard to anaylze the accuracy of the results or even who might have made a referral or received referral rewards. 

It might be useful to consider building an API and table similar to `eligible-donation` where we can see all the referral relationships across a period of time.

For every referral donation we could show:

- txHash, date, USD value of donation, donorAddress, donorName, USD value of referral rewards, referrerAddress, referrerName


since we won't have the GIVbacks amount until we calculate a price of GIV we can only estimate the USD value of their referral reward. If we're able to see all of this data somehow separate from the rest of donation data it will be much easier to analyze.

then maybe we can show a new column in GIVbacks calculation showing how much they earned or lost from referrals, if applicable. 

### using your example as an example :smile: : 

example: user A make a donation with 100$ value, A send a referral link to user B and that user donate to a verified project with 200$ value, now when calculating givback reward we assume, **user A has donated (100 + 10% * 200) = 120$ and user B has donated 200 * 90% = 180$ and we calculate givbacks based on this info.** 

- GIV price is 0.2

under column heading `referralRewards`

User A = +100 ($20 / 0.2)
User B = -100 ($20 / 0.2)
User C = 0 or empty (they did not interact with the referral program)

## What do you think?

**Comment by mohammadranjbarz** [comment]
> > @CarlosQ96 has implemented impact-graph side and I implemented givback-calculation side, now it's implemented and deployed on https://givback.develop.giveth.io/api-docs/#/default/get_calculate, @divine-comedian as you are the best one who is familiar with givback-calculation API I would appreciate if you can test it
> > 
> > 1. We use a fraction of eligible donations to referrer if donations is referral ( now it's 10 percent but its configurable)
> > 2. It doesn't matter if referrer is in purple list or not, we distribute reward for him
> > 3. If the user that came with the referral link is a new donor we will give a referral reward to the referrer for the current round and the next round
> > 4. If the use that came with the referral link is not a new donor we will give reward for next 24 hours ( 24 hours from when user clicked on link, and also the time is configurable)
> > 5. example: user **A** make a donation with 100$ value, **A** send a referral link to user **B** and that user donate to a verified project with 200$ value, now when calculating givback reward we assume, user **A** has donated (100 + 10% * 200) = `120$`  and user **B** has donated 200 * 90% = `180$` and we calculate givbacks based on this info
> 
> Understood, however since we mix in referral donations with all the other donation data (on production) it is hard to anaylze the accuracy of the results or even who might have made a referral or received referral rewards.
> 
> It might be useful to consider building an API and table similar to `eligible-donation` where we can see all the referral relationships across a period of time.
> 
> For every referral donation we could show:
> 
> * txHash, date, USD value of donation, donorAddress, donorName, USD value of referral rewards, referrerAddress, referrerName
> 
> since we won't have the GIVbacks amount until we calculate a price of GIV we can only estimate the USD value of their referral reward. If we're able to see all of this data somehow separate from the rest of donation data it will be much easier to analyze.
> 
> then maybe we can show a new column in GIVbacks calculation showing how much they earned or lost from referrals, if applicable.
> 
> ### using your example as an example 😄 :
> example: user A make a donation with 100$ value, A send a referral link to user B and that user donate to a verified project with 200$ value, now when calculating givback reward we assume, **user A has donated (100 + 10% * 200) = 120$ and user B has donated 200 * 90% = 180$ and we calculate givbacks based on this info.**
> 
> * GIV price is 0.2
> 
> under column heading `referralRewards`
> 
> User A = +100 ($20 / 0.2) User B = -100 ($20 / 0.2) User C = 0 or empty (they did not interact with the referral program)
> 
> ## What do you think?

Nice, Thanks @divine-comedian  for your great feedbacks, I'll try to start implementing them at the beginning of next week

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Now we have two fields
named: ** isReferrerGivbackEligible**, ** referrerWallet** in eligible donations response, so you can know if the donations have referrer or not, and the referrer is eligible to get reward or not

<img width="1272" alt="Screen Shot 1402-01-14 at 17 06 53" src="https://user-images.githubusercontent.com/9850545/229526300-03c3d1e1-34e5-49b0-8702-f949b40d2b3e.png">

in the other hand, in /calculate response we have an array named `givbacks` that show each user how much donated and how much givbacks would receive, in this array I added these values to each item:

  **totalReferralDeductedUsdValue**, **totalReferralDeductedUsdValueAfterGivFactor**, **totalReferralAddedUsdValue**, **totalReferralAddedUsdValueAfterGivFactor**
  With these params you can know each user how much recieved referral rewards, or how much deducted from that user's donations, aggregating all those data in a new webservice needs more time and I think makes our codes complex, but if you think you need it I can do that ( but as I my time is almost limited, and I think with current data we can test the referral reward flow I guess we can go forward)
<img width="553" alt="Screen Shot 1402-01-14 at 17 08 57" src="https://user-images.githubusercontent.com/9850545/229526974-46563405-6131-46d9-977d-812a17219244.png">

**Comment by divine-comedian** [comment]
thanks @mohammadranjbarz 

These upgrades make it definitely possible to test, I checked it out today and can confirm the flow seems to be working as expected. 

- eligible donations made show if they were made by a referral link and shows who the wallet owner is
- we can cross-reference giverAddress in `eligible-donations` to addresses in `calculate` to find the relationship between referrers and referrals
- amounts appear to be added and subtracted appropriately between the different referral users
- all referral donations that appear on chainvine are accounted for in the database

**Comment by MoeNick** [comment]
@maryjaf can you confirm it? if so put in done please

**Comment by WhyldWanderer** [comment]
Is it possible to add the totalReferralAddedAfterGivFactor in GIV tokens?
Right now it is only in USD. 

I would like to add this to the forum post in the form of GIV tokens if possible. I will manually add it this round (33)

**Comment by WhyldWanderer** [comment]
actually nvm.. I can just use a formula in the spreadsheet
