### ISSUE TITLE
Backend for Estimate Matching

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#988]
Fork what Gitcoin did:

https://github.com/gitcoinco/web/tree/master/app/grants

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/30273b35-d5c4-4861-9f49-6d3663bcb711)

**Comment by MoeNick** [comment]
This is the correct link:
https://github.com/gitcoinco/web/tree/master/app/grants

@mohammadranjbarz @aminlatifi do you need more information to implement this?

**Comment by mohammadranjbarz** [comment]
This link return `404`
<img width="1825" alt="Screen Shot 1402-02-24 at 16 43 49" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/75339a84-5a31-43e4-abb6-c3da37586554">

Anyway , @laurenluz  Do we have to use reverse engineering, don't we have any specific algorithm or formula for calculating an estimated match?
I think if someone provides that formula it's not only easier to implement but also make it easier for @maryjaf  to test it later

**Comment by MoeNick** [comment]
I edited the link by adding "s" at the end of url

**Comment by laurenluz** [comment]
double check that link that moenick sent @mohammadranjbarz

we shouldn't have to do much reverse engineering, we should be able just to fork the code that gitcon already created.

**Comment by aminlatifi** [comment]
I could find this js implementation of QF
https://github.com/Anish-Agnihotri/quadratic-funding/blob/3e173091a5058faf6d44bebdb346262b62596dbb/pages/index.js#L84-L115

It explains the logic in js, in order to have this data per project in the backend we must provision some APIs and processes

**Comment by aminlatifi** [comment]
> I could find this js implementation of QF https://github.com/Anish-Agnihotri/quadratic-funding/blob/3e173091a5058faf6d44bebdb346262b62596dbb/pages/index.js#L84-L115
> 
> It explains the logic in js, in order to have this data per project in the backend we must provision some APIs and processes
 
The link above is the source code of https://wtfisqf.com/?grant=&grant=&grant=&grant=&match=1000

The logic is in this part
<img width="810" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/02c58ffc-ef1c-4447-b15c-d28c5607b8af">


In PR #1009 my plan was to create an API which response
1. Current active qf round `allocatedFound`
2. The sum of square root of donations to the project. In case of above code, is `sumAmount` before be squared (its value till line 100)
3. The value corresponding to `summed`
4. contributors to the project in the current round
5. total contributors in this round

**Comment by MoeNick** [comment]
Related PR:
https://github.com/Giveth/impact-graph/pull/1009/commits

**Comment by aminlatifi** [comment]
As a continue to  this comment https://github.com/Giveth/giveth-dapps-v2/issues/2650#issuecomment-1574812155
I think we must do some modifications to the backend
1- First remove redundant `getProjectDonationsSqrtRootSumToThePowerOfTwo` and `getQfRoundTotalProjectsDonationsSum` methods. 
2- Replace all queries related to matching to Materialized Views and refresh them on every new donation or change in the active QF Round state if matters. These queries are complex and the frontend needs them on projects list, so it will kill the backend if we run the query for each project even if they are cached. Therefore, we can make materialized views for 
 - [x] Replace `getProjectDonationsSqrtRootSum` per project with a materialized view
 - [ ] Replace  `countUniqueDonors` per project (it's regardless of QF round and only needs to be updated on donations) with a materialized view
 - [x] Replace `getQfRoundTotalProjectsDonationsSum`. I am not sure it's good to replace it with materialized view, because it's single row table. We can have it as it is with long expiration cache
 - [ ] Remove `countUniqueDonorsForActiveQfRound`, the `getProjectDonationsSqrtRootSum` has this data.
 - [ ] Remove `sumDonationValueUsdForActiveQfRound`, the `getProjectDonationsSqrtRootSum` has it.

**Comment by mohammadranjbarz** [comment]
> 

Ok got it, I will jump to it today after my current task, or Monday

**Comment by CarlosQ96** [comment]
Ok, I agree. I think the issue is mainly in the project view, with the design the matching is present in all projects cards. so a view is ideal.

**Comment by mohammadranjbarz** [comment]
Demo for calculating estimated matching
https://wtfisqf.com/?grant=&grant=&grant=&grant=&match=1000

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  @MohammadPCh 

Now we have all calculation requirements deployed on develop, you can use it

https://github.com/Giveth/impact-graph/pull/1014#issuecomment-1587252273
